"use client";

import React, { useState } from "react";
import { Avatar, Badge, Button, Chip, Drawer, Icon, Paper, SearchInput, Select, Switch, Tabs, Text, Textarea, Title } from "@bayesstack/ui";

const helpTopics = [
  { title: "Learning", detail: "Courses, concepts, activities, and studios", icon: "BookOpen", count: "18 guides", tone: "indigo" },
  { title: "Labs & practicals", detail: "Preparation, sessions, evidence, journal, and viva", icon: "Notebook", count: "24 guides", tone: "teal" },
  { title: "Projects", detail: "Teams, milestones, submissions, and contribution", icon: "Folder", count: "12 guides", tone: "violet" },
  { title: "Assessments", detail: "Attempts, deadlines, feedback, and grades", icon: "ShieldCheck", count: "16 guides", tone: "amber" },
  { title: "Discussions", detail: "Context, visibility, escalation, and resolution", icon: "Comment", count: "9 guides", tone: "blue" },
  { title: "Account & access", detail: "Profile, accessibility, connections, and privacy", icon: "User", count: "14 guides", tone: "slate" },
];

export function HelpExperience() {
  const [reportOpen, setReportOpen] = useState(false);
  const [search, setSearch] = useState("");
  return <div className="support-page support-page-v2">
    <section className="support-search-hero"><div className="support-search-orb" aria-hidden="true" /><Badge color="info" variant="outline" prefixIcon="Sparkles">BayesStack support</Badge><Title as="h1" weight="semibold">How can we help?</Title><Text as="p" size="lg">Find an answer, get help with your current work, or reach the right person without losing context.</Text><SearchInput value={search} onValueChange={setSearch} onClear={() => setSearch("")} size="lg" placeholder="Search help, for example “submit lab evidence”" aria-label="Search help" /><div className="support-popular-v2"><span>Popular:</span>{["Submit work","Join a lab","Assessment feedback","Keyboard access"].map((item) => <button key={item} onClick={() => setSearch(item)}>{item}</button>)}</div></section>

    <section className="support-command-grid">
      <Paper className="support-context-v2" radius="xl" elevation="lg" padding={24}><div className="support-context-icon"><Icon name="Notebook" size="lg" /></div><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Help for where you are</Text><Title as="h2" weight="semibold">Optimization Lab / Tune learning rate</Title><Text as="p" size="sm" color="secondary">We can already see the activity, workspace type, and current step. Diagnostic details remain private unless you include them.</Text><div><Chip size="sm" color="success" variant="subtle" prefixIcon="CheckCircle">Context ready</Chip><Chip size="sm" color="neutral" variant="outline">Step 3 of 5</Chip></div></div><Button variant="outline" size="sm" rightIcon="ArrowRight">View related help</Button></Paper>
      <Paper className="support-route-card" radius="xl" elevation="md" padding={22}><div><span className="is-academic"><Icon name="Comment" size="md" /></span><div><Text as="p" size="xs" color="tertiary" strong>Academic question?</Text><Title as="h3" weight="semibold">Ask with learning context</Title></div></div><Text as="p" size="sm" color="secondary">Get help from Bayes AI, classmates, or faculty.</Text><Button variant="link" size="sm" rightIcon="ArrowRight">Go to discussions</Button></Paper>
      <Paper className="support-route-card" radius="xl" elevation="md" padding={22}><div><span className="is-technical"><Icon name="Settings" size="md" /></span><div><Text as="p" size="xs" color="tertiary" strong>Technical issue?</Text><Title as="h3" weight="semibold">Report it with diagnostics</Title></div></div><Text as="p" size="sm" color="secondary">Send the current route and error context to support.</Text><Button variant="link" size="sm" rightIcon="ArrowRight" onClick={() => setReportOpen(true)}>Report a problem</Button></Paper>
    </section>

    <section className="support-browse-v2"><div className="support-v2-section-heading"><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Browse by workspace</Text><Title as="h2" weight="semibold">Answers shaped around learner tasks</Title></div><Button variant="link" size="sm" rightIcon="ArrowRight">View all guides</Button></div><div>{helpTopics.map((topic) => <Paper as="article" hoverable radius="xl" elevation="md" padding={20} className={`support-topic-v2 is-${topic.tone}`} key={topic.title}><span><Icon name={topic.icon as any} size="md" /></span><Title as="h3" weight="semibold">{topic.title}</Title><Text as="p" size="sm" color="secondary">{topic.detail}</Text><footer><small>{topic.count}</small><Icon name="ArrowRight" size="xs" /></footer></Paper>)}</div></section>

    <section className="support-bottom-v2"><Paper radius="xl" elevation="md" padding={22} className="support-shortcuts-v2"><div><span><Icon name="Command" size="md" /></span><div><Text as="p" size="xs" color="tertiary" strong>Keyboard access</Text><Title as="h3" weight="semibold">Move quickly without a mouse</Title></div></div><div><span><strong>Search</strong><kbd>Ctrl K</kbd></span><span><strong>Navigation</strong><kbd>Alt N</kbd></span><Button variant="link" size="sm" rightIcon="ArrowRight">All shortcuts</Button></div></Paper><Paper radius="xl" elevation="md" padding={22} className="support-status-v2"><span className="support-status-dot" /><div><Text as="p" size="xs" color="tertiary" strong>Platform status</Text><Title as="h3" weight="semibold">All systems operational</Title><Text as="p" size="xs" color="tertiary">Last checked just now</Text></div><Button variant="outline" size="sm">View status</Button></Paper></section>
    <ProblemDrawer open={reportOpen} onClose={() => setReportOpen(false)} />
  </div>;
}

function ProblemDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [sent, setSent] = useState(false);
  const [description, setDescription] = useState("");
  return <Drawer open={open} onClose={onClose} title="What went wrong?" subtitle="Report a technical problem" size="md" className="support-drawer-v2" footer={sent ? <Button variant="outline" onClick={onClose}>Done</Button> : <><Button variant="outline" onClick={onClose}>Cancel</Button><Button rightIcon="ArrowRight" onClick={() => setSent(true)}>Send report</Button></>}>{sent ? <div className="support-sent-v2"><span><Icon name="CheckCircle" size="lg" /></span><Title as="h2" weight="semibold">Report sent</Title><Text as="p" size="md" color="secondary">The relevant learning and diagnostic context was attached. Support will follow up in your institutional email.</Text><Badge color="success" variant="subtle">Reference BS-4821</Badge></div> : <><Paper variant="subtle" radius="lg" elevation="none" padding={15} className="support-attached-v2"><Icon name="Notebook" size="sm" /><span><strong>Optimization Lab / Step 3</strong><small>Current route and workspace attached</small></span><Badge color="success" variant="subtle" size="sm">Attached</Badge></Paper><div className="support-report-field"><Text as="label" size="sm" strong>Describe the problem</Text><Textarea value={description} onValueChange={setDescription} rows={6} placeholder="The notebook does not load after I run the cell..." showCount maxLength={800} /></div><label className="support-diagnostic-v2"><Switch defaultChecked aria-label="Include diagnostic information" /><span><strong>Include diagnostic information</strong><small>Browser, device, current route, and error identifier</small></span></label><Button variant="outline" size="sm" leftIcon="File">Add screenshot</Button></>}</Drawer>;
}

type ProfileTabName = "Profile" | "Preferences" | "Connections" | "Privacy";

export function ProfileExperience() {
  const [tab, setTab] = useState<ProfileTabName>("Profile");
  return <div className="profile-page profile-page-v2">
    <section className="profile-hero-v2"><div className="profile-cover-v2"><span /><i /></div><div className="profile-identity-v2"><Avatar name="Sarah Connor" size="xl" status="online" /><div><Badge color="success" variant="subtle" prefixIcon="ShieldCheck">Institution verified</Badge><Title as="h1" weight="semibold">Sarah Connor</Title><Text as="p" size="md" color="secondary">M.Sc. Data Science / Semester 2</Text><Text as="p" size="sm" color="tertiary">Veermata Jijabai Technological Institute</Text></div><div><Button variant="outline" size="sm" leftIcon="Edit">Edit profile</Button><Button variant="outline" size="sm" leftIcon="Eye">Preview</Button></div></div><div className="profile-trust-row"><span><Icon name="ShieldCheck" size="sm" /><strong>Academic identity</strong><small>Managed by your institution</small></span><span><Icon name="Globe" size="sm" /><strong>Private capability profile</strong><small>Visible only when you choose</small></span><span><Icon name="Link" size="sm" /><strong>2 connected sources</strong><small>Permissions reviewed Sep 1</small></span></div></section>
    <Tabs className="profile-tabs-v2" value={tab} onValueChange={(value) => setTab(value as ProfileTabName)} variant="pill" size="sm" items={[{ value: 'Profile', label: 'Profile' }, { value: 'Preferences', label: 'Preferences' }, { value: 'Connections', label: 'Connections', badge: <span>2</span> }, { value: 'Privacy', label: 'Privacy' }]} />
    {tab === 'Profile' ? <ProfileTab /> : tab === 'Preferences' ? <PreferencesTab /> : tab === 'Connections' ? <ConnectionsTab /> : <PrivacyTab />}
  </div>;
}

function ProfileTab() {
  return <div className="profile-content-grid"><div><InfoSection title="Personal information" icon="User" rows={[["Display name","Sarah Connor",false],["Preferred name","Sarah",true],["Email","sarah.connor@university.edu",false],["Timezone","Asia/Kolkata",true],["Language","English",true]]} /><InfoSection title="Academic information" icon="BookOpen" rows={[["Institution","VJTI",false],["Program","M.Sc. Data Science",false],["Current term","Semester 2 / Spring 2026",false],["Enrollment status","Active",false],["Student ID","•••• 4821",false]]} /></div><aside><Paper radius="xl" elevation="md" padding={22} className="profile-completeness-v2"><div className="learner-panel-heading"><div><Text as="p" size="xs" color="tertiary" strong>Profile readiness</Text><Title as="h2" weight="semibold">Almost complete</Title></div><Badge color="success" variant="subtle">86%</Badge></div><div className="profile-completeness-ring"><span style={{ '--profile-progress': '86%' } as React.CSSProperties}><i /></span><div><strong>Add a preferred learning language</strong><small>Helps recommendations and accessibility defaults.</small></div></div><Button variant="outline" size="sm" fullWidth>Complete profile</Button></Paper><Paper radius="xl" elevation="md" padding={22} className="profile-account-v2"><Text as="p" size="xs" color="tertiary" strong>Account access</Text><span><Icon name="ShieldCheck" size="sm" /><div><strong>Institutional SSO</strong><small>Signed in through VJTI</small></div></span><span><Icon name="CheckCircle" size="sm" /><div><strong>Secure session</strong><small>Last verified today, 09:02</small></div></span><Button variant="link" size="sm">Sign out</Button></Paper></aside></div>;
}

function InfoSection({ title, icon, rows }: { title: string; icon: string; rows: Array<[string,string,boolean]> }) {
  return <Paper className="profile-info-v2" radius="xl" elevation="md" padding={0}><header><span><Icon name={icon as any} size="sm" /></span><Title as="h2" weight="semibold">{title}</Title></header>{rows.map(([label,value,editable]) => <div key={label}><span>{label}</span><strong>{value}</strong>{editable ? <Button variant="link" size="xs">Edit</Button> : <Badge color="neutral" variant="subtle" size="sm">Institution managed</Badge>}</div>)}</Paper>;
}

function PreferencesTab() {
  const notifications = ["Deadlines", "Faculty feedback", "Discussion replies", "Project mentions", "Learning recommendations", "Institution announcements"];
  return <div className="profile-settings-grid"><Paper radius="xl" elevation="md" padding={0} className="profile-settings-panel"><header><span><Icon name="Notification" size="sm" /></span><div><Title as="h2" weight="semibold">Notifications</Title><Text as="p" size="sm" color="secondary">Choose which learning signals deserve your attention.</Text></div></header>{notifications.map((item,index) => <label key={item}><span><strong>{item}</strong><small>{index < 2 ? 'Recommended for timely academic progress' : 'Delivered through your selected channels'}</small></span><Switch defaultChecked={index !== 4} aria-label={item} /></label>)}<div className="profile-select-row"><span><strong>Digest frequency</strong><small>Non-urgent updates</small></span><Select defaultValue="daily" options={[{ value: 'daily', label: 'Daily digest' }, { value: 'weekly', label: 'Weekly digest' }, { value: 'off', label: 'Off' }]} /></div></Paper><Paper radius="xl" elevation="md" padding={0} className="profile-settings-panel"><header><span><Icon name="Eye" size="sm" /></span><div><Title as="h2" weight="semibold">Display & accessibility</Title><Text as="p" size="sm" color="secondary">Set a comfortable default across every BayesStack workspace.</Text></div></header>{[["Theme","System"],["Text size","Default"],["Motion","Reduced"],["Contrast","Standard"]].map(([label,value]) => <div className="profile-select-row" key={label}><span><strong>{label}</strong><small>Applies across studios</small></span><Select defaultValue={value.toLowerCase()} options={[{ value: value.toLowerCase(), label: value }, { value: 'alternate', label: 'Alternate' }]} /></div>)}<Button variant="link" size="sm" rightIcon="ArrowRight">View keyboard shortcuts</Button></Paper></div>;
}

function ConnectionsTab() {
  const connections = [["GitHub","Connected as sarahconnor","Connected","Code"],["LinkedIn","Not connected","Connect","Link"],["Stack Overflow","Not connected","Connect","Comment"],["Institutional records","Managed by VJTI","Managed","BookOpen"],["Certifications","No provider connected","Connect","Award"]];
  return <div className="connections-view-v2"><Paper className="connections-intro-v2" radius="xl" elevation="lg" padding={26}><span><Icon name="Link" size="lg" /></span><div><Badge color="success" variant="subtle" prefixIcon="ShieldCheck">Permission controlled</Badge><Title as="h2" weight="semibold">Bring permitted evidence into one trustworthy skill snapshot.</Title><Text as="p" size="md" color="secondary">You decide what connects, what BayesStack may read, and whether any evidence becomes visible.</Text></div></Paper><div className="connection-grid-v2">{connections.map(([name,state,action,icon]) => <Paper as="article" hoverable radius="xl" elevation="md" padding={20} key={name}><span className="connection-icon-v2"><Icon name={icon as any} size="md" /></span><div><Title as="h3" weight="semibold">{name}</Title><Text as="p" size="xs" color="tertiary">{state}</Text></div><Badge color={action === 'Connected' ? 'success' : action === 'Managed' ? 'neutral' : 'primary'} variant="subtle" size="sm">{action}</Badge><Button variant="outline" size="sm" fullWidth>{action === 'Connect' ? 'Connect' : 'Review permissions'}</Button></Paper>)}</div></div>;
}

function PrivacyTab() {
  return <div className="privacy-view-v2"><Paper className="privacy-hero-v2" radius="xl" elevation="lg" padding={26}><span><Icon name="ShieldCheck" size="lg" /></span><div><Badge color="success" variant="subtle">Private by default</Badge><Title as="h2" weight="semibold">Your capability record belongs to you.</Title><Text as="p" size="md" color="secondary">Academic staff see only what their teaching role requires. Career targets and external evidence remain private unless you choose otherwise.</Text></div></Paper><Paper className="privacy-settings-v2" radius="xl" elevation="md" padding={0}><header><Title as="h2" weight="semibold">Visibility</Title><Text as="p" size="sm" color="secondary">Review exactly what other people can discover.</Text></header>{[["Name & photo","Classmates in my courses"],["Program","Classmates in my courses"],["Skills & capability","Only me"],["Career targets","Only me"],["Evidence portfolio","Only me"]].map(([label,setting],index) => <div key={label}><span><strong>{label}</strong><small>{index < 2 ? 'Supports academic collaboration' : 'Sensitive learner information'}</small></span><Select defaultValue={setting} options={[{ value: setting, label: setting }, { value: 'Only me', label: 'Only me' }, { value: 'Institution', label: 'Authorized institution staff' }]} /></div>)}</Paper></div>;
}
