"use client";

import React, { useState } from "react";
import { Avatar, AvatarsGroup, Badge, Button, Chip, Icon, LoadingBar, Paper, ProgressRing, Tabs, Text, Title } from "@bayesstack/ui";

export type LearnerWorkScreen = "labs" | "lab-course" | "lab-overview" | "lab-session" | "lab-studio" | "projects" | "project-cockpit";
type LabId = "optimization" | "instrumentation" | "chemistry";

type LabDefinition = {
  title: string; course: string; mode: "Digital" | "Physical" | "Hybrid"; phase: string; action: string; due: string; progress: number;
  description: string; activities: string[];
};

const labs: Record<LabId, LabDefinition> = {
  optimization: { title: "Optimization Lab", course: "ML 401 / Chapter 2", mode: "Digital", phase: "Practical", action: "Continue workspace", due: "Due tomorrow, 14:00", progress: 60, description: "Apply gradient-based optimization to train and diagnose a linear model.", activities: ["Review problem setup", "Run baseline experiment", "Tune learning rate", "Interpret convergence", "Submit notebook"] },
  instrumentation: { title: "Electronic Instrumentation Practical", course: "Electronic Instrumentation Laboratory", mode: "Physical", phase: "Pre-lab", action: "Prepare for lab", due: "Session Tue, 14:00", progress: 42, description: "Prepare for and document the frequency-response experiment in the physical laboratory.", activities: ["Safety briefing", "Procedure review", "Physical practical session", "Observation sheet", "Journal certification", "Viva"] },
  chemistry: { title: "Synthesis and Characterisation", course: "CHEM 214 / Experimental Chemistry", mode: "Hybrid", phase: "Post-lab", action: "Complete lab report", due: "Report due Friday, 16:00", progress: 70, description: "Analyse results from the scheduled chemistry practical and submit a laboratory report.", activities: ["Risk assessment", "In-person practical", "Experimental data", "Analysis", "Laboratory report"] },
};

function Progress({ value, label }: { value: number; label?: string }) {
  return <div className="work-progress"><LoadingBar progress={value} height={5} />{label && <small>{label}</small>}</div>;
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <header className="work-page-header"><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">{eyebrow}</Text><Title as="h1" weight="semibold">{title}</Title><Text as="p" size="md" color="secondary">{description}</Text></div>{action}</header>;
}

export function LabProjectExperience({ screen, onScreenChange }: { screen: LearnerWorkScreen; onScreenChange: (screen: LearnerWorkScreen) => void }) {
  const [selectedLab, setSelectedLab] = useState<LabId>("optimization");
  const openLab = (lab: LabId) => { setSelectedLab(lab); onScreenChange("lab-overview"); };
  if (screen === "lab-studio") return <LabStudio onBack={() => onScreenChange("lab-overview")} />;
  if (screen === "lab-session") return <PhysicalSession onBack={() => onScreenChange("lab-overview")} />;
  if (screen === "lab-overview") return <LabOverview lab={labs[selectedLab]} onBack={() => onScreenChange(selectedLab === "instrumentation" ? "lab-course" : "labs")} onAction={() => onScreenChange(selectedLab === "optimization" ? "lab-studio" : selectedLab === "instrumentation" ? "lab-session" : "lab-overview")} />;
  if (screen === "lab-course") return <LabCourse onBack={() => onScreenChange("labs")} onOpenExperiment={() => openLab("instrumentation")} />;
  if (screen === "project-cockpit") return <ProjectCockpit onBack={() => onScreenChange("projects")} />;
  if (screen === "projects") return <ProjectsLanding onOpen={() => onScreenChange("project-cockpit")} />;
  return <LabsLanding onOpenLab={openLab} onOpenCourse={() => onScreenChange("lab-course")} />;
}

function LabsLanding({ onOpenLab, onOpenCourse }: { onOpenLab: (lab: LabId) => void; onOpenCourse: () => void }) {
  const [filter, setFilter] = useState("All labs");
  const cards: Array<[LabId, string]> = [["optimization", "Continue"], ["instrumentation", "Prepare"], ["chemistry", "Complete report"]];
  return <div className="work-page work-page-v2">
    <PageHeader eyebrow="Practice & evidence" title="Labs" description="Prepare, perform, and prove what you can do across digital, physical, and hybrid practical work." action={<Badge color="warning" variant="subtle" size="md" prefixIcon="Calendar">1 session this week</Badge>} />
    <Tabs className="work-filter-tabs-v2" value={filter} onValueChange={setFilter} variant="pill" size="sm" items={[{ value: "All labs", label: "All labs", badge: <span>4</span> }, { value: "Preparing", label: "Preparing" }, { value: "In progress", label: "In progress" }, { value: "Reports & viva", label: "Reports & viva" }]} />
    <section className="lab-command-grid">
      <Paper className="lab-feature-card" radius="xl" elevation="lg" bordered={false} padding={0}>
        <div className="lab-feature-copy"><div className="lab-feature-top"><Badge color="warning" variant="subtle" prefixIcon="MapPin">Physical session</Badge><span>Tuesday / 14:00</span></div><Text as="p" size="sm">EI Laboratory / Batch B</Text><Title as="h2" weight="semibold">Electronic Instrumentation Practical</Title><Text as="p" size="md">Complete the safety briefing and procedure review before arriving at your allocated bench.</Text><div className="lab-feature-states"><span className="is-done"><Icon name="CheckCircle" size="xs" /> Equipment allocated</span><span className="is-done"><Icon name="CheckCircle" size="xs" /> Journal ready</span><span><Icon name="Clock" size="xs" /> Attendance on arrival</span></div><Button size="md" rightIcon="ArrowRight" onClick={() => onOpenLab("instrumentation")}>Prepare for lab</Button></div>
        <div className="lab-feature-visual"><ProgressRing value={42} size={132} thickness={9} color="#f4c56b" trackColor="rgba(255,255,255,.14)" label={<span><strong>42%</strong><small>prepared</small></span>} /><div><span>Next requirement</span><strong>Safety and procedure review</strong><small>About 12 minutes</small></div></div>
      </Paper>
      <Paper className="lab-readiness-panel" radius="xl" elevation="md" padding={24}>
        <div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Practical readiness</Text><Title as="h2" weight="semibold">Everything in one workflow</Title></div>
        {[['Prepare','Instructions, risk and prerequisites','CheckCircle'],['Perform','Studio or scheduled laboratory','Notebook'],['Prove','Evidence, report and viva','ShieldCheck']].map(([title, detail, icon], index) => <div className="lab-readiness-step" key={title}><i>{index + 1}</i><span><strong>{title}</strong><small>{detail}</small></span><Icon name={icon as any} size="sm" /></div>)}
        <Text as="p" size="xs" color="tertiary">Faculty retains final academic judgement throughout.</Text>
      </Paper>
    </section>
    <section className="work-list-section work-list-section-v2"><div className="work-section-heading"><div><p className="work-kicker">Your practical work</p><h2>Continue where evidence is moving</h2></div><Button variant="link" size="sm" rightIcon="ArrowRight">View completed labs</Button></div><div className="lab-card-grid lab-card-grid-v2">{cards.map(([id, label]) => { const lab = labs[id]; return <Paper as="article" hoverable radius="xl" elevation="md" padding={22} className={`lab-card-v2 is-${lab.mode.toLowerCase()}`} key={id}><div className="lab-card-top"><span className="lab-card-symbol"><Icon name={lab.mode === "Digital" ? "Code" : lab.mode === "Physical" ? "MapPin" : "Layers"} size="md" /></span><Badge color={lab.mode === "Digital" ? "primary" : lab.mode === "Physical" ? "warning" : "info"} variant="subtle" size="sm">{lab.mode}</Badge></div><Text as="p" size="xs" color="tertiary" strong>{lab.phase}</Text><Title as="h3" weight="semibold">{lab.title}</Title><Text as="p" size="sm" color="secondary">{lab.course}</Text><div className="lab-card-deadline"><Icon name="Clock" size="xs" /><span>{lab.due}</span></div><Progress value={lab.progress} label={`${lab.progress}% complete`} /><Button variant="outline" size="sm" fullWidth rightIcon="ArrowRight" onClick={() => id === "instrumentation" ? onOpenCourse() : onOpenLab(id)}>{label}</Button></Paper>; })}</div></section>
  </div>;
}

function LabCourse({ onBack, onOpenExperiment }: { onBack: () => void; onOpenExperiment: () => void }) {
  const [tab, setTab] = useState("Experiments");
  const experiments = ["Bridge rectifier characteristics", "Transistor amplifier biasing", "Op-amp integrator", "Frequency response of amplifier", "Digital multimeter calibration", "Oscilloscope measurements", "Signal generator analysis", "Instrumentation viva preparation"];
  return <div className="work-page work-page-v2 lab-course-page">
    <button className="work-back" onClick={onBack}><Icon name="ArrowLeft" size="xs" /> Labs</button>
    <PageHeader eyebrow="Standalone practical course" title="Electronic Instrumentation Laboratory" description="A physical laboratory course with term work, journal, practical examination and viva." action={<div className="lab-course-code">EI LAB / Spring 2026</div>} />
    <Tabs className="lab-course-tabs-v2" value={tab} onValueChange={setTab} variant="pill" size="sm" items={[{ value: 'Experiments', label: 'Experiments', badge: <span>8</span> }, { value: 'Evidence & assessment', label: 'Evidence & assessment' }, { value: 'Practical examination', label: 'Practical examination' }]} />
    {tab === "Experiments" ? <><Paper className="lab-course-health-v2" radius="xl" elevation="md" padding={0}><div><Badge color="success" variant="subtle" prefixIcon="Notebook">Term work on track</Badge><Text as="p" size="sm">Required practical record</Text><Title as="h2" weight="semibold">5 of 8 experiments completed</Title><Text as="p" size="sm" color="secondary">Your journal evidence is current and the next physical session is ready to prepare.</Text><div><Button size="sm" rightIcon="ArrowRight" onClick={onOpenExperiment}>Prepare Practical 06</Button><Button variant="link" size="sm">View course guide</Button></div></div><aside><ProgressRing value={62} size={112} thickness={8} color="#55af94" trackColor="#e4eeeb" label={<span><strong>62%</strong><small>term work</small></span>} /><span><Icon name="CheckCircle" size="sm" /><strong>Journal certified</strong><small>Last signed Sep 10</small></span></aside></Paper><section className="experiment-list experiment-list-v2">{experiments.map((item, index) => <button key={item} onClick={index === 5 ? onOpenExperiment : undefined} className={index < 5 ? "is-complete" : index === 5 ? "is-current" : ""}><i>{index < 5 ? <Icon name="CheckCircle" size="xs" /> : String(index + 1).padStart(2, "0")}</i><span><strong>Practical {String(index + 1).padStart(2, "0")}: {item}</strong><small>{index < 5 ? "Evidence verified" : index === 5 ? "Prepare for Tuesday session" : "Not started"}</small></span><em>{index < 5 ? "Complete" : index === 5 ? "Open" : "Upcoming"}</em><Icon name="ChevronRight" size="xs" /></button>)}</section></> : tab === "Evidence & assessment" ? <AssessmentPanel /> : <PracticalExam />}
  </div>;
}

function AssessmentPanel() {
  return <section className="assessment-layout"><div className="assessment-breakdown"><p className="work-kicker">Assessment composition</p><h2>Continuous and final assessment</h2>{[["Practical performance", "30%"], ["Journal / lab book", "20%"], ["Viva", "20%"], ["Final practical examination", "30%"]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="evidence-stack"><p className="work-kicker">Evidence on record</p>{[["Faculty observation", "5 practicals verified"], ["Journal / lab book", "Certified Sep 10"], ["Instrument output", "3 result sheets"], ["Attendance", "91%"], ["Viva", "Due at final practical"]].map(([type, detail]) => <div key={type}><Icon name="CheckCircle" size="xs" /><span><strong>{type}</strong><small>{detail}</small></span></div>)}</div></section>;
}

function PracticalExam() {
  return <section className="practical-exam"><div><p className="work-kicker">Final practical</p><h2>Sep 28 / 10:00 - 13:00</h2><p>Physics Laboratory 2 / Batch B</p><div className="exam-roles"><span><Icon name="Users" size="sm" /> Internal examiner assigned</span><span><Icon name="Users" size="sm" /> External examiner assigned</span></div></div><aside><p className="work-kicker">Eligibility</p><span><Icon name="CheckCircle" size="xs" /> Minimum experiments completed</span><span><Icon name="CheckCircle" size="xs" /> Journal certified</span><span><Icon name="CheckCircle" size="xs" /> Attendance requirement met</span><strong>Eligible to attend</strong></aside></section>;
}

function LabOverview({ lab, onBack, onAction }: { lab: LabDefinition; onBack: () => void; onAction: () => void }) {
  const [activity, setActivity] = useState(0);
  const [reportOpen, setReportOpen] = useState(false);
  const isPhysical = lab.mode === "Physical";
  const action = lab.mode === "Hybrid" && reportOpen ? "Report draft saved" : lab.action;
  return <div className="work-page work-page-v2 lab-overview-page">
    <button className="work-back" onClick={onBack}><Icon name="ArrowLeft" size="xs" /> {isPhysical ? "Electronic Instrumentation Laboratory" : "Labs"}</button>
    <PageHeader eyebrow={`${lab.course} / ${lab.mode} workflow`} title={lab.title} description={lab.description} action={<span className={`lab-mode-badge is-${lab.mode.toLowerCase()}`}>{lab.mode} execution</span>} />
    <Paper className="lab-action-summary-v2" radius="xl" elevation="lg" bordered={false} padding={0}><div><Badge color={lab.mode === 'Physical' ? 'warning' : 'success'} variant="outline" prefixIcon={lab.mode === 'Physical' ? 'MapPin' : 'Code'}>Current phase / {lab.phase}</Badge><Title as="h2" weight="semibold">{action}</Title><Text as="p" size="md">{isPhysical ? "Your session is scheduled for Tuesday at 14:00. Finish preparation before arrival." : lab.mode === "Hybrid" ? "Your practical is complete. Analyse your data and add the report evidence." : "Your digital workspace is ready. Continue the current experiment when you are ready."}</Text><div className="lab-action-meta-v2"><span><Icon name="Clock" size="xs" /><strong>{lab.due}</strong><small>Official academic schedule</small></span><span><Icon name="ShieldCheck" size="xs" /><strong>{isPhysical ? 'Faculty observed' : 'Execution verified'}</strong><small>Evidence stays attached</small></span></div><Button size="md" rightIcon={lab.mode === 'Hybrid' ? 'Edit' : 'ArrowRight'} onClick={() => lab.mode === "Hybrid" ? setReportOpen(true) : onAction()}>{action}</Button></div><aside><ProgressRing value={lab.progress} size={128} thickness={9} color={lab.mode === 'Physical' ? '#f2c36b' : '#80e2c6'} trackColor="rgba(255,255,255,.14)" label={<span><strong>{lab.progress}%</strong><small>complete</small></span>} /><div>{lab.activities.slice(0,3).map((item,index) => <span className={index < (isPhysical ? 1 : 2) ? 'is-done' : index === activity ? 'is-current' : ''} key={item}><i>{index < (isPhysical ? 1 : 2) ? <Icon name="CheckCircle" size="xs" /> : null}</i>{item}</span>)}</div></aside></Paper>
    {isPhysical && <Paper className="lab-session-card-v2" radius="xl" elevation="md" padding={18}><span className="lab-session-date-v2"><small>TUE</small><strong>15</strong></span><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Scheduled session</Text><Title as="h2" weight="semibold">14:00 - 17:00</Title><Text as="p" size="sm" color="secondary">Physics Laboratory 2 / Batch B / Demonstrator: Dr. Mehta</Text></div><div><Chip color="success" variant="subtle" size="sm" prefixIcon="CheckCircle">Equipment allocated</Chip><span><Icon name="Users" size="xs" /> Attendance recorded on arrival</span></div><Button variant="outline" size="sm" rightIcon="ArrowRight">Session details</Button></Paper>}
    <section className="lab-workflow-section"><div className="work-section-heading"><div><p className="work-kicker">Lab activities</p><h2>{isPhysical ? "Configurable practical workflow" : "Current workflow"}</h2></div><span>Activities vary by lab</span></div><ol className="lab-activity-list">{lab.activities.map((item, index) => <li key={item} className={index < (isPhysical ? 1 : 2) ? "is-complete" : index === activity ? "is-current" : ""}><button onClick={() => setActivity(index)}><i>{index < (isPhysical ? 1 : 2) ? <Icon name="CheckCircle" size="xs" /> : String(index + 1).padStart(2, "0")}</i><span><strong>{item}</strong><small>{index === 0 ? "Verified" : index === activity ? "Current action" : "Required evidence follows this activity"}</small></span>{index === activity && <em>Current</em>}</button></li>)}</ol></section>
    <section className="lab-info-grid"><article><p className="work-kicker">Required evidence</p><ul>{(isPhysical ? ["Faculty-observed performance", "Observation sheet", "Certified journal entry"] : lab.mode === "Hybrid" ? ["Experimental data", "Analysis workbook", "Laboratory report"] : ["Notebook execution", "Experiment results", "Written interpretation"]).map((item) => <li key={item}>{item}</li>)}</ul></article><article><p className="work-kicker">Assessment</p><div className="assessment-mini"><span>Continuous assessment</span><strong>In progress</strong><span>{isPhysical ? "Performance, journal, viva" : "Evidence and outcome checks"}</span></div><button className="work-text-button">View assessment criteria <Icon name="ArrowRight" size="xs" /></button></article><article><p className="work-kicker">People and rules</p><div className="rules-mini"><span><Icon name="Users" size="xs" /> Faculty verification enabled</span><span><Icon name="CheckCircle" size="xs" /> Evidence counts toward eligibility</span><span><Icon name="ShieldCheck" size="xs" /> Final judgement remains faculty-led</span></div></article></section>
    {reportOpen && <section className="report-draft"><Icon name="CheckCircle" size="sm" /><div><strong>Laboratory report draft started</strong><p>Experimental data is attached. Your report remains editable until Friday, 16:00.</p></div><button className="work-outline-button">Open report <Icon name="ArrowRight" size="xs" /></button></section>}
  </div>;
}

function PhysicalSession({ onBack }: { onBack: () => void }) {
  const [signed, setSigned] = useState(false);
  return <div className="physical-session"><header><button onClick={onBack}><Icon name="ArrowLeft" size="sm" /> Electronic Instrumentation Practical</button><span>Batch B / Physics Laboratory 2</span><span><Icon name="Clock" size="xs" /> 14:00 - 17:00</span></header><main><section className="physical-session-brief"><p className="work-kicker">Physical practical</p><h1>Oscilloscope measurements</h1><p>Determine the frequency response of the amplifier using the allocated bench equipment.</p><div><span><Icon name="CheckCircle" size="sm" /> Attendance recorded</span><span><Icon name="CheckCircle" size="sm" /> Safety briefing complete</span></div></section><section className="physical-observation"><div><p className="work-kicker">Observed performance</p><h2>Faculty verification</h2>{["Setup assembled correctly", "Measurement procedure followed", "Results recorded in journal"].map((item, index) => <label key={item}><input type="checkbox" defaultChecked={index < 2} /> {item}</label>)}</div><aside><p className="work-kicker">Evidence to attach</p><span>Observation sheet</span><span>Instrument output</span><span>Journal entry</span><button className="work-primary-button" onClick={() => setSigned(true)}>{signed ? "Examiner signed off" : "Examiner sign-off"} <Icon name="CheckCircle" size="xs" /></button></aside></section><section className="physical-session-footer"><span><Icon name="Users" size="sm" /> Demonstrator: Dr. Mehta</span><span>Manual academic judgement is recorded with your evidence.</span></section></main></div>;
}

function LabStudio({ onBack }: { onBack: () => void }) {
  const [checked, setChecked] = useState(false);
  return <div className="lab-studio"><header className="lab-studio-topbar"><button onClick={onBack}><Icon name="ArrowLeft" size="sm" /><span>Optimization Lab</span></button><span className="lab-studio-step">Activity 3 of 5</span><span className="lab-studio-saved"><Icon name="CheckCircle" size="xs" /> Saved</span><span className="lab-studio-time"><Icon name="Clock" size="xs" /> 42 min</span><button className="lab-submit">Submit evidence</button></header><div className="lab-studio-grid"><aside className="lab-guide"><p>Lab activities</p><ol>{["Problem setup", "Baseline experiment", "Tune learning rate", "Interpret results", "Submit notebook"].map((step, index) => <li key={step} className={index < 2 ? "is-complete" : index === 2 ? "is-current" : ""}><i>{index < 2 ? <Icon name="CheckCircle" size="xs" /> : index + 1}</i><span>{step}</span></li>)}</ol></aside><main className="lab-workspace"><header><div><Icon name="Notebook" size="sm" /><strong>gradient_descent_lab.ipynb</strong><span>Python 3.13</span></div><button><Icon name="Play" size="xs" /> Run all</button></header><div className="notebook-page"><section className="notebook-copy"><small>ACTIVITY 3</small><h1>Tune the learning rate</h1><p>Use the update rule below to compare stable and unstable convergence. Record what changes as the learning rate increases.</p></section><section className="notebook-code"><div><span>Python</span><button><Icon name="Play" size="xs" /> Run</button></div><pre>{`learning_rate = 0.1\nweights = [0.0]\n\nfor step in range(24):\n    gradient = 2 * (weights[-1] - 3)\n    weights.append(weights[-1] - learning_rate * gradient)\n\nplot_loss(weights)`}</pre></section><section className="notebook-output"><strong>Loss over iterations</strong><div className="loss-chart"><i /><i /><i /><i /><i /><b /></div><span>Converged in 24 steps / Final loss 0.0002</span></section><label className="notebook-response">Observation<textarea placeholder="What changes when learning_rate is set to 1.2?" /><small>Your response is saved automatically.</small></label></div></main><aside className="lab-context"><p>Context</p><div><small>Expected evidence</small><h2>Learning-rate comparison</h2><p>Loss curves for three values and a short observation of convergence behaviour.</p></div><section><small>Assessment</small><ul><li>Execution checks guide your work</li><li>Faculty releases final judgement</li></ul></section><button className="work-primary-button" onClick={() => setChecked(true)}>Check work <Icon name="CheckCircle" size="xs" /></button>{checked && <section className="lab-check-results"><strong>3 checks passed</strong><span><Icon name="CheckCircle" size="xs" /> Gradient has correct dimensionality</span><span><Icon name="CheckCircle" size="xs" /> Numerical gradient matches</span><span className="is-hint"><Icon name="HelpCircle" size="xs" /> Inspect loss after iteration 18.</span></section>}<button className="lab-help"><Icon name="AiChat" size="sm" /> Ask in context</button></aside></div></div>;
}

function ProjectsLanding({ onOpen }: { onOpen: () => void }) {
  return <div className="work-page work-page-v2 projects-page-v2"><PageHeader eyebrow="Create & demonstrate" title="Projects" description="Persistent team workspaces where open-ended problems become attributable, credible evidence." action={<div className="project-counts-v2"><span><b>2</b><small>Active</small></span><span><b>4</b><small>Completed</small></span></div>} />
    <Paper className="project-hero-v2" radius="xl" elevation="lg" bordered={false} padding={0}>
      <div className="project-hero-main"><div className="project-hero-label"><Badge color="success" variant="subtle" prefixIcon="Folder">Active capstone</Badge><span>29 days remaining</span></div><Text as="p" size="sm">ML 401 / Machine Learning</Text><Title as="h2" weight="semibold">Customer Churn Prediction</Title><Text as="p" size="md">Build, evaluate, and defend an end-to-end prediction system with a traceable contribution record.</Text><div className="project-team-v2"><AvatarsGroup avatars={[{ name: 'Sarah Connor', color: '#dff7f0' }, { name: 'Arjun Jain', color: '#e7e9ff' }, { name: 'Neha Kapoor', color: '#fff0d8' }]} total={4} limit={3} size="sm" /><span><strong>Team Orbit</strong><small>4 members / Contribution tracking on</small></span></div><Button size="md" rightIcon="ArrowRight" onClick={onOpen}>Enter project workspace</Button></div>
      <div className="project-hero-status"><ProgressRing value={68} size={126} thickness={9} color="#7e8bf2" trackColor="rgba(255,255,255,.14)" label={<span><strong>68%</strong><small>complete</small></span>} /><div className="project-milestone-track">{[['Problem framing','done'],['Data & baseline','done'],['Model evaluation','current'],['Final defence','next']].map(([label,state]) => <span className={`is-${state}`} key={label}><i>{state === 'done' ? <Icon name="CheckCircle" size="xs" /> : null}</i>{label}</span>)}</div></div>
    </Paper>
    <div className="project-insight-grid">
      <Paper radius="xl" elevation="md" padding={24} className="project-next-panel"><div className="learner-panel-heading"><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Your next contribution</Text><Title as="h2" weight="semibold">Compare candidate models</Title></div><Badge color="warning" variant="subtle">Due Sep 19</Badge></div><Text as="p" size="sm" color="secondary">Explain why the selected metric fits an imbalanced dataset and attach the comparison output.</Text><div className="project-contribution-meta"><span><Icon name="Target" size="sm" /> Evaluation report</span><span><Icon name="ShieldCheck" size="sm" /> Individually attributable</span><span><Icon name="Clock" size="sm" /> About 45 min</span></div><Button variant="outline" size="sm" rightIcon="ArrowRight" onClick={onOpen}>Continue my work</Button></Paper>
      <Paper radius="xl" elevation="md" padding={24} className="project-team-panel"><div className="learner-panel-heading"><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Team pulse</Text><Title as="h2" weight="semibold">Two decisions need you</Title></div><Icon name="Comment" size="md" /></div><div className="project-team-update"><Avatar name="Aarav Jain" size="sm" /><span><strong>Aarav proposed F1-score</strong><small>Model evaluation / 22 min ago</small></span><Badge color="info" variant="subtle">Mention</Badge></div><div className="project-team-update"><Avatar name="Neha Kapoor" size="sm" /><span><strong>Dataset note is ready</strong><small>Data preparation / 1 hr ago</small></span><Icon name="CheckCircle" size="sm" /></div><Button variant="secondary" size="sm" fullWidth leftIcon="Comment" onClick={onOpen}>Open project discussion</Button></Paper>
    </div>
  </div>;
}

function ProjectCockpit({ onBack }: { onBack: () => void }) {
  const [tab, setTab] = useState("Overview");
  return <div className="work-page work-page-v2 project-cockpit project-cockpit-v2">
    <button className="work-back" onClick={onBack}><Icon name="ArrowLeft" size="xs" /> Projects</button>
    <PageHeader eyebrow="ML 401 / Capstone / Team Orbit" title="Customer Churn Prediction" description="Build, evaluate, and defend an end-to-end prediction system with a traceable contribution record." action={<div className="project-cockpit-people"><AvatarsGroup avatars={[{ name: 'Sarah Connor', color: '#dff7f0' }, { name: 'Aarav Jain', color: '#e7e9ff' }, { name: 'Neha Kapoor', color: '#fff0d8' }]} total={4} limit={3} size="sm" /><span><strong>Team Orbit</strong><small>4 members / Due Oct 12</small></span></div>} />
    <Tabs className="project-cockpit-tabs" value={tab} onValueChange={setTab} variant="pill" size="sm" items={[{ value: 'Overview', label: 'Overview' }, { value: 'Work', label: 'Work', badge: <span>2</span> }, { value: 'Milestones', label: 'Milestones' }, { value: 'Evidence', label: 'Evidence', badge: <span>14</span> }, { value: 'Feedback', label: 'Feedback', badge: <span>1</span> }]} />

    <section className="project-cockpit-command">
      <Paper className="project-current-milestone" radius="xl" elevation="lg" bordered={false} padding={0}><div><Badge color="success" variant="outline" prefixIcon="Target">Current milestone</Badge><Text as="p" size="sm">Milestone 3 of 4</Text><Title as="h2" weight="semibold">Model evaluation</Title><Text as="p" size="md">Choose a defensible evaluation approach, compare candidate models, and document the decision.</Text><div className="project-milestone-facts"><span><Icon name="Calendar" size="xs" /><strong>Due Sep 19</strong><small>6 days remaining</small></span><span><Icon name="ShieldCheck" size="xs" /><strong>3 evidence checks</strong><small>2 already satisfied</small></span><span><Icon name="Comment" size="xs" /><strong>Faculty checkpoint</strong><small>Sep 20 / 11:30</small></span></div><Button size="md" rightIcon="ArrowRight" onClick={() => setTab('Work')}>Continue my work</Button></div><aside><ProgressRing value={68} size={124} thickness={9} color="#82dec5" trackColor="rgba(255,255,255,.14)" label={<span><strong>68%</strong><small>complete</small></span>} /><div>{[['Problem framing','done'],['Data & baseline','done'],['Model evaluation','current'],['Final defence','next']].map(([label,state]) => <span className={`is-${state}`} key={label}><i>{state === 'done' ? <Icon name="CheckCircle" size="xs" /> : null}</i>{label}</span>)}</div></aside></Paper>
      <Paper className="project-cockpit-pulse" radius="xl" elevation="md" padding={22}><div className="learner-panel-heading"><div><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Your contribution</Text><Title as="h2" weight="semibold">Clear and attributable</Title></div><Badge color="success" variant="subtle">On track</Badge></div><div className="project-contribution-ring"><ProgressRing value={72} size={92} thickness={8} color="#5d70df" trackColor="#e8eafa" label={<strong>72%</strong>} /><span><strong>6 evidence items</strong><small>4 verified / 2 in review</small></span></div><div className="project-cockpit-stats"><span><b>3</b><small>commits</small></span><span><b>2</b><small>decisions</small></span><span><b>1</b><small>review</small></span></div><Button variant="outline" size="sm" fullWidth onClick={() => setTab('Evidence')}>Review my evidence</Button></Paper>
    </section>

    <ProjectCockpitContent tab={tab} onTabChange={setTab} />
  </div>;
}

function ProjectCockpitContent({ tab, onTabChange }: { tab: string; onTabChange: (tab: string) => void }) {
  if (tab === "Milestones") return <section className="project-cockpit-section"><div className="work-section-heading"><div><p className="work-kicker">Delivery path</p><h2>Four milestones, one evidence trail</h2></div><Badge color="primary" variant="subtle">68% complete</Badge></div><Paper className="project-cockpit-milestones" radius="xl" elevation="md" padding={0}>{[["01","Problem framing","Research question and success definition","Complete"],["02","Data & baseline","Dataset note, quality review, baseline model","Complete"],["03","Model evaluation","Metric decision and comparison report","In progress"],["04","Final defence","Demonstration, report, and viva","Upcoming"]].map(([number,title,detail,state]) => <div className={`is-${state.toLowerCase().replace(' ','-')}`} key={number}><i>{state === 'Complete' ? <Icon name="CheckCircle" size="sm" /> : number}</i><span><strong>{title}</strong><small>{detail}</small></span><Badge color={state === 'Complete' ? 'success' : state === 'In progress' ? 'primary' : 'neutral'} variant="subtle">{state}</Badge><Button variant="link" size="sm" rightIcon="ArrowRight">View</Button></div>)}</Paper></section>;

  if (tab === "Evidence") return <section className="project-cockpit-section"><div className="work-section-heading"><div><p className="work-kicker">Contribution record</p><h2>What you did—and what it demonstrates</h2></div><Button variant="outline" size="sm" leftIcon="File">Export evidence</Button></div><Paper className="project-cockpit-evidence" radius="xl" elevation="md" padding={0}>{[["Sep 13","Model comparison notebook","Model Evaluation","Verified"],["Sep 12","F1-score decision note","Analytical Reasoning","In review"],["Sep 09","Baseline model commit","Python / Scikit-learn","Verified"],["Sep 06","Dataset quality analysis","Data Preparation","Verified"]].map(([date,title,capability,status],index) => <div key={title}><time>{date}</time><span><Icon name={index === 1 ? 'Comment' : index === 3 ? 'ChartLine' : 'Code'} size="sm" /></span><span><strong>{title}</strong><small>{capability} / Attributed to Sarah Connor</small></span><Badge color={status === 'Verified' ? 'success' : 'warning'} variant="subtle" prefixIcon={status === 'Verified' ? 'CheckCircle' : 'Clock'}>{status}</Badge><Icon name="ChevronRight" size="xs" /></div>)}</Paper></section>;

  if (tab === "Feedback") return <section className="project-cockpit-section"><div className="work-section-heading"><div><p className="work-kicker">Feedback</p><h2>Guidance connected to the work</h2></div><Badge color="warning" variant="subtle">1 unread</Badge></div><div className="project-feedback-grid"><Paper radius="xl" elevation="md" padding={24}><div className="project-feedback-person"><Avatar name="Prof. N. Rao" size="sm" /><span><strong>Prof. N. Rao</strong><small>Faculty checkpoint / Today, 09:10</small></span><Badge color="primary" variant="subtle">Faculty</Badge></div><Text as="p" size="md" color="secondary">Your comparison is clear. Add the class distribution beside the F1-score rationale so the metric decision can be understood without opening the notebook.</Text><footer><Chip color="warning" variant="subtle" size="sm">Action requested</Chip><Button variant="outline" size="sm" rightIcon="ArrowRight" onClick={() => onTabChange('Work')}>Open related work</Button></footer></Paper><Paper radius="xl" elevation="md" padding={24} className="project-feedback-context"><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Attached context</Text><Title as="h3" weight="semibold">F1-score decision note</Title><div><span>Balanced accuracy</span><strong>0.74</strong></div><div><span>F1-score</span><strong>0.71</strong></div><Badge color="success" variant="subtle" prefixIcon="Link">Evidence linked</Badge></Paper></div></section>;

  return <section className="project-cockpit-section"><div className="work-section-heading"><div><p className="work-kicker">{tab === 'Work' ? 'Active workspace' : 'Your next decision'}</p><h2>Compare candidate models</h2></div><Badge color="warning" variant="subtle">Due Sep 19</Badge></div><div className="project-decision-grid"><Paper className="project-model-comparison" radius="xl" elevation="md" padding={0}><header><span><Text as="p" size="xs" color="tertiary" strong>MODEL</Text><Text as="p" size="xs" color="tertiary" strong>ROC-AUC</Text><Text as="p" size="xs" color="tertiary" strong>F1-SCORE</Text><Text as="p" size="xs" color="tertiary" strong>DECISION</Text></span></header>{[["Logistic baseline","0.81","0.58","Baseline"],["Class-weighted LR","0.83","0.68","Candidate"],["XGBoost","0.87","0.71","Recommended"]].map(([model,auc,f1,state],index) => <button className={index === 2 ? 'is-selected' : ''} key={model}><span><i><Icon name={index === 2 ? 'CheckCircle' : 'ChartLine'} size="sm" /></i><strong>{model}</strong><small>{index === 0 ? 'Team baseline' : index === 1 ? 'Interpretable trade-off' : 'Best minority-class recall'}</small></span><b>{auc}</b><b>{f1}</b><Badge color={index === 2 ? 'success' : 'neutral'} variant="subtle">{state}</Badge></button>)}<footer><span><Icon name="ShieldCheck" size="sm" /><strong>Decision evidence required</strong><small>Explain why F1-score fits the imbalanced target.</small></span><Button size="sm" rightIcon="ArrowRight">Open comparison notebook</Button></footer></Paper><aside className="project-decision-rail"><Paper radius="xl" elevation="md" padding={20}><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Definition of done</Text>{[["Comparison output attached",true],["Metric rationale written",true],["Error analysis included",false],["Peer decision acknowledged",false]].map(([label,done]) => <span key={String(label)} className={done ? 'is-done' : ''}><Icon name={done ? 'CheckCircle' : 'Clock'} size="sm" />{label as string}</span>)}<Progress value={50} label="2 of 4 ready" /></Paper><Paper radius="xl" elevation="md" padding={20}><Text as="p" size="xs" color="tertiary" strong className="learner-panel-eyebrow">Team activity</Text>{[["AJ","Aarav proposed F1-score","22 min"],["NK","Neha attached dataset note","1 hr"]].map(([initials,title,time]) => <div key={title}><Avatar name={initials} size="xs" /><span><strong>{title}</strong><small>{time} ago</small></span></div>)}<Button variant="link" size="sm" rightIcon="ArrowRight">Open discussion</Button></Paper></aside></div></section>;
}
